### ISSUE TITLE
使用方法没看懂

### ISSUE THREAD

**Issue by FJSEN** [mydansun/ielts.cn_hkj#2]
怎么用 我还是没看懂.....链接放在地址栏里了，然后呢》？单击 没反应 ，请指导一下

**Comment by yangxu1231** [comment]
先在网页登录你的雅思账号，然后点击f12，进入console页面，然后打开ielts.js（用记事本），然后复制粘贴到刚才的console中，回车，然后在左侧就会出现了，完成

**Comment by FJSEN** [comment]
> 先在网页登录你的雅思账号，然后点击f12，进入console页面，然后打开ielts.js（用记事本），然后复制粘贴到刚才的console中，回车，然后在左侧就会出现了，完成

我一会再试一下，感谢大侠

**Comment by FJSEN** [comment]
Thanks， I’ll try it ,later. Thanks one more time

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: yangxu1231 <notifications@github.com>
发送时间: Sunday, March 8, 2020 2:11:45 PM
收件人: mydansun/ielts.cn_hkj <ielts.cn_hkj@noreply.github.com>
抄送: FJSEN <wsmagicalempire@hotmail.com>; Author <author@noreply.github.com>
主题: Re: [mydansun/ielts.cn_hkj] 使用方法没看懂 (#2)


先在网页登录你的雅思账号，然后点击f12，进入console页面，然后打开ielts.js（用记事本），然后复制粘贴到刚才的console中，回车，然后在左侧就会出现了，完成

―

**Comment by liaoqiqi666** [comment]
您好，怎么实现加拿大雅思自动刷考位？非常需要！

**Comment by liaoqiqi666** [comment]
您好，补充如何实现加拿大雅思自动刷考位？非常需要！有偿！！千米

**Comment by ZxyElaine** [comment]
> 

请问成功了吗？能请教一下吗，我粘贴后回车运行没有反应

**Comment by ZxyElaine** [comment]
> 先在网页登录你的雅思账号，然后点击f12，进入console页面，然后打开ielts.js（用记事本），然后复制粘贴到刚才的console中，回车，然后在左侧就会出现了，完成

你好，能详细讲解下吗？请问加入标签以后，是在哪一步点标签页呢？

**Comment by yangxu1231** [comment]
您好，我记得这是很久之前的代码了吧？具体记不太清了。但是据我了解现在的雅思官网已经更新了，这个大概率是没法用了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mydansun/ielts.cn_hkj"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月9日(星期天) 中午1:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mydansun/ielts.cn_hkj] 使用方法没看懂 (#2)





  
先在网页登录你的雅思账号，然后点击f12，进入console页面，然后打开ielts.js（用记事本），然后复制粘贴到刚才的console中，回车，然后在左侧就会出现了，完成
  
你好，能详细讲解下吗？请问加入标签以后，是在哪一步点标签页呢？
