### ISSUE TITLE
在指定页面下点击脚本没有反应

### ISSUE THREAD

**Issue by JinChengneng** [mydansun/ielts.cn_hkj#5]
我在如下页面点击收藏夹中的脚本，但是并没有反应。使用的浏览器为edge，请问具体应该如何操作？

```
https://ielts.neea.cn/myHome/XXXXXXXX/index#!/querySeat?productType=IELTSPBT
```

**Comment by mydansun** [comment]
edge浏览器版本 111.0.1661.62测试了下是可以的。检查下收藏夹的链接是否是`javascript:`开头，并且本机网络可以访问 https://www.jsdelivr.com/
